#pragma once

#include <stdio.h>
#include <assert.h>
#include <tchar.h>
#include <iostream>
#include <string>
#include <memory>
#include <iostream>
#include <fstream>
#include <array>
#include <algorithm>
#include <vector>
#include <Ws2tcpip.h>
#include <ctime>
#include <signal.h>
#include <thread>
#include <mutex>
#include <map>
